on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client
      - uses: actions/setup-go@v2
      - run: cd client && go build .
      - uses: actions/upload-artifact@v2
        with:
          name: client
          path: ./client/client
