on: push

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: cd client
      - uses: actions/setup-go@v2
      - run: cd client && go build .
      - uses: actions/upload-artifact@v2
        with:
          name: client-${{ matrix.os }}
          path: ./client/client
